### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by aure** [protometa/audio-kit-debug#1]
I figure we could have faster conversations here.

**Comment by aure** [comment]
Can you put this as the last line of VDL:

`print("View did load finished with amplitude = \(oscillator.amplitude)")`

When I do I get:

```
VDL
View did load finished with amplitude = 0.0
```

What do you get?

**Comment by protometa** [comment]
Yeah I get `View did load finished with amplitude = 0.0` 😞

**Comment by aure** [comment]
Can I add you to screenhero?
